name: burnout_buster
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.6
  local_auth: ^3.0.0
  flutter_secure_storage: ^10.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
